#!/anaconda/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mrbait==1.1.6','console_scripts','mrbait'
__requires__ = 'mrbait==1.1.6'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mrbait==1.1.6', 'console_scripts', 'mrbait')()
    )
