#!/usr/bin/python

string = "TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAATGAAAAAA-GAAAAAAAAAAAAAAAGAATAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAGNT"

sub = string[105:126]
print(sub)
print(len(sub))
